[package]
name = "function-plotter"
version = "0.4.0"
edition = "2024"
description = "Программа для построения графиков функций"
license = "MIT"
repository = "https://github.com/afaist/function-plotter"
authors = ["Alexander Zinovev",]

[dependencies]
eframe = "0.36"
egui = "0.36"
image = { version = "0.25", features = ["png"] }
mathexpr = "0.1.1"
dirs = "7.0.0"
rfd = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
